/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.5 */

#include "remote.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(prometheus_MetricMetadata, prometheus_MetricMetadata, AUTO)


PB_BIND(prometheus_WriteRequest, prometheus_WriteRequest, AUTO)




